spring:
  ai:
    mistralai:
      chat:
        options:
          model: mistral-large-latest
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
